const ADD_TODO = 'todo/ADD_TODO'
const UPDATE_TODO = 'todo/UPDATE_TODO'
const REMOVE_TODO = 'todo/REMOVE_TODO'

const CHANGE_SCREEN = 'change/CHANGE_SCREEN'

const FETCH_TODOS = 'db/FETCH_TODOS'
const SHOW_LOADER = 'db/SHOW_LOADER'
const HIDE_LOADER = 'db/HIDE_LOADER'
const SHOW_ERROR = 'db/SHOW_ERROR'
const CLEAR_ERROR = 'db/CLEAR_ERROR'

export default {
  ADD_TODO,
  UPDATE_TODO,
  REMOVE_TODO,
  CHANGE_SCREEN,
  FETCH_TODOS,
  SHOW_LOADER,
  HIDE_LOADER,
  SHOW_ERROR,
  CLEAR_ERROR,
}
